### ISSUE TITLE
Alternate costumes won’t work if Holiday Mod is activated

### ISSUE THREAD

**Issue by TinaRussell** [MainMemory/SA2CharSel#2]
The character select mod works for me, but when I tried playing as Rouge with her alternate costume it didn’t work (she just had her normal costume)—until I deactivated the Holiday Mod (Month ver.), which, since it’s April, wasn’t doing anything at present anyway. Just to be sure, I did check to see if it made a difference if I had the Holiday Mod loaded after the Character Select mod instead of before, but the same thing happened—no alternate costumes in single-player, unless I deactivated the Holiday Mod entirely.
In any case, this is a great mod. It’s such fun gliding around as lingerie dominatrix Rouge, hehehehh!

**Comment by MainMemory** [comment]
This sounds like an issue with the holiday mod, not the character select mod.
